import { PERMISSIONS, Permission } from './permissions';

export enum RoleType {
  SUPER_ADMIN = 'super_admin',
  ORG_ADMIN = 'org_admin',
  SITE_MANAGER = 'site_manager',
  SUPERVISOR = 'supervisor',
  EMPLOYEE = 'employee',
  AUDITOR = 'auditor',
}

export interface RoleDefinition {
  type: RoleType;
  description: string;
  scope: 'platform' | 'organization' | 'site';
  permissions: Permission[];
}

export const ROLE_DEFINITIONS: Record<RoleType, RoleDefinition> = {
  [RoleType.SUPER_ADMIN]: {
    type: RoleType.SUPER_ADMIN,
    description: 'Platform operator with full access across all tenants',
    scope: 'platform',
    permissions: Object.values(PERMISSIONS), // All permissions
  },
  [RoleType.ORG_ADMIN]: {
    type: RoleType.ORG_ADMIN,
    description: 'Organization admin with full access within their tenant',
    scope: 'organization',
    permissions: [
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.USERS_VIEW, PERMISSIONS.USERS_CREATE, PERMISSIONS.USERS_UPDATE, PERMISSIONS.USERS_DELETE,
      PERMISSIONS.SITES_VIEW, PERMISSIONS.SITES_CREATE, PERMISSIONS.SITES_UPDATE, PERMISSIONS.SITES_DELETE,
      PERMISSIONS.TEMPERATURE_VIEW, PERMISSIONS.TEMPERATURE_CREATE, PERMISSIONS.TEMPERATURE_UPDATE,
      PERMISSIONS.CHECKLISTS_VIEW, PERMISSIONS.CHECKLISTS_CREATE, PERMISSIONS.CHECKLISTS_UPDATE, PERMISSIONS.CHECKLISTS_APPROVE,
      PERMISSIONS.TRACEABILITY_VIEW, PERMISSIONS.TRACEABILITY_CREATE, PERMISSIONS.TRACEABILITY_UPDATE,
      PERMISSIONS.CORRECTIVE_VIEW, PERMISSIONS.CORRECTIVE_CREATE, PERMISSIONS.CORRECTIVE_APPROVE,
      PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
      PERMISSIONS.NFC_SCAN, PERMISSIONS.NFC_MANAGE,
      PERMISSIONS.HACCP_VIEW, PERMISSIONS.HACCP_CREATE, PERMISSIONS.HACCP_UPDATE, PERMISSIONS.HACCP_APPROVE,
      PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.SETTINGS_UPDATE,
      PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_ASSIGN,
      PERMISSIONS.AUDIT_VIEW,
    ],
  },
  [RoleType.SITE_MANAGER]: {
    type: RoleType.SITE_MANAGER,
    description: 'Facility manager with access limited to their specific site(s)',
    scope: 'site',
    permissions: [
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.USERS_VIEW,
      PERMISSIONS.SITES_VIEW,
      PERMISSIONS.TEMPERATURE_VIEW, PERMISSIONS.TEMPERATURE_CREATE, PERMISSIONS.TEMPERATURE_UPDATE,
      PERMISSIONS.CHECKLISTS_VIEW, PERMISSIONS.CHECKLISTS_CREATE, PERMISSIONS.CHECKLISTS_UPDATE, PERMISSIONS.CHECKLISTS_APPROVE,
      PERMISSIONS.TRACEABILITY_VIEW, PERMISSIONS.TRACEABILITY_CREATE, PERMISSIONS.TRACEABILITY_UPDATE,
      PERMISSIONS.CORRECTIVE_VIEW, PERMISSIONS.CORRECTIVE_CREATE, PERMISSIONS.CORRECTIVE_APPROVE,
      PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
      PERMISSIONS.NFC_SCAN, PERMISSIONS.NFC_MANAGE,
      PERMISSIONS.HACCP_VIEW,
      PERMISSIONS.SETTINGS_VIEW,
      PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_ASSIGN,
    ],
  },
  [RoleType.SUPERVISOR]: {
    type: RoleType.SUPERVISOR,
    description: 'Shift leader who can approve some actions and view reports',
    scope: 'site',
    permissions: [
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.TEMPERATURE_VIEW, PERMISSIONS.TEMPERATURE_CREATE,
      PERMISSIONS.CHECKLISTS_VIEW, PERMISSIONS.CHECKLISTS_CREATE, PERMISSIONS.CHECKLISTS_UPDATE, PERMISSIONS.CHECKLISTS_APPROVE,
      PERMISSIONS.TRACEABILITY_VIEW, PERMISSIONS.TRACEABILITY_CREATE,
      PERMISSIONS.CORRECTIVE_VIEW, PERMISSIONS.CORRECTIVE_CREATE,
      PERMISSIONS.NFC_SCAN,
      PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_ASSIGN,
    ],
  },
  [RoleType.EMPLOYEE]: {
    type: RoleType.EMPLOYEE,
    description: 'Kitchen staff who can submit data and complete tasks',
    scope: 'site',
    permissions: [
      PERMISSIONS.TEMPERATURE_VIEW, PERMISSIONS.TEMPERATURE_CREATE,
      PERMISSIONS.CHECKLISTS_VIEW, PERMISSIONS.CHECKLISTS_CREATE,
      PERMISSIONS.TRACEABILITY_VIEW, PERMISSIONS.TRACEABILITY_CREATE,
      PERMISSIONS.CORRECTIVE_CREATE,
      PERMISSIONS.NFC_SCAN,
      PERMISSIONS.TASKS_VIEW,
    ],
  },
  [RoleType.AUDITOR]: {
    type: RoleType.AUDITOR,
    description: 'External inspector with read-only access',
    scope: 'organization',
    permissions: [
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.SITES_VIEW,
      PERMISSIONS.TEMPERATURE_VIEW,
      PERMISSIONS.CHECKLISTS_VIEW,
      PERMISSIONS.TRACEABILITY_VIEW,
      PERMISSIONS.CORRECTIVE_VIEW,
      PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
      PERMISSIONS.HACCP_VIEW,
      PERMISSIONS.AUDIT_VIEW,
    ],
  },
};
